# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grammar.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grammar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgrammar.proto\x12\x07grammar\x1a\x1bgoogle/protobuf/empty.proto\"Q\n\x0e\x43learTextError\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\r\n\x05index\x18\x03 \x01(\x05\x12\x13\n\x0bsuggestions\x18\x04 \x03(\t\" \n\x0eGrammarRequest\x12\x0e\n\x06tokens\x18\x01 \x03(\t\"b\n\x0fGrammarResponse\x12\x16\n\x0e\x63orrected_text\x18\x01 \x01(\t\x12\'\n\x06\x65rrors\x18\x02 \x03(\x0b\x32\x17.grammar.ClearTextError\x12\x0e\n\x06tokens\x18\x03 \x03(\t2\x8b\x01\n\x0eGrammarService\x12\x41\n\x0c\x43heckGrammar\x12\x17.grammar.GrammarRequest\x1a\x18.grammar.GrammarResponse\x12\x36\n\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grammar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLEARTEXTERROR']._serialized_start=55
  _globals['_CLEARTEXTERROR']._serialized_end=136
  _globals['_GRAMMARREQUEST']._serialized_start=138
  _globals['_GRAMMARREQUEST']._serialized_end=170
  _globals['_GRAMMARRESPONSE']._serialized_start=172
  _globals['_GRAMMARRESPONSE']._serialized_end=270
  _globals['_GRAMMARSERVICE']._serialized_start=273
  _globals['_GRAMMARSERVICE']._serialized_end=412
# @@protoc_insertion_point(module_scope)
