KEYBOARD_NEIGHBORS = {
    "q": "was",
    "w": "qeasd",
    "e": "wsdr",
    "r": "edft",
    "t": "rfgy",
    "y": "tghu",
    "u": "yhji",
    "i": "ujko",
    "o": "iklp",
    "p": "ol",
    "a": "qwsz",
    "s": "qwedxza",
    "d": "wersfxc",
    "f": "ertdgcv",
    "g": "rtyfhbv",
    "h": "tyugjbn",
    "j": "yuihknm",
    "k": "uioljmn",
    "l": "opk",
    "z": "asx",
    "x": "zsdc",
    "c": "xdfv",
    "v": "cfgb",
    "b": "vghn",
    "n": "bhjm",
    "m": "njk",
}
